### ISSUE TITLE
Hotlink "Something wrong with this article? Help us out by opening an issue or pull request on GitHub"?

### ISSUE THREAD

**Issue by mohawk2** [dnmfarrell/perldotcom#32]
It would be even easier to suggest a correction if the above text were hotlinked to e.g. https://github.com/dnmfarrell/perldotcom/edit/master/content/article/a-hackerspace-webcam.md

**Comment by dnmfarrell** [comment]
Great idea, thanks!

**Comment by dnmfarrell** [comment]
Done and live!
