### ISSUE TITLE
Perl.com twitter feed

### ISSUE THREAD

**Issue by briandfoy** [dnmfarrell/perldotcom#33]
Right now it's just the twitter feed for The Perl Foundation. I think we should hook up Perlybot to publish its feed to twitter.

**Comment by dnmfarrell** [comment]
Perlybot is on [Twitter](https://twitter.com/PerlyBot)!

**Comment by briandfoy** [comment]
I mean that this website should have its own dedicated twitter feed (as
well as being syndicated into other twitter feeds).

**Comment by dnmfarrell** [comment]
Ah I see what you mean. During the site refresh I discussed that with Jim and he wanted the Perl Foundation account to be "the feed" for the site. I've added perl.com to the Perly Bot feeds file though.
