### ISSUE TITLE
search form has no explicit "trigger search" button

### ISSUE THREAD

**Issue by wchristian** [dnmfarrell/perldotcom#42]
This can present problems for browsers/keyboard combos where no enter key is present. (Certain mobile devices.)

**Comment by dnmfarrell** [comment]
Any idea which mobile devices are affected by this? I've tested it on my android phone and I can search. I will test it on an iPhone later.

**Comment by briandfoy** [comment]
It works fine on the iPhone.

**Comment by dnmfarrell** [comment]
Closing as it works fine on IOS and Android.

**Comment by wchristian** [comment]
*tests only on the latest version* "WORKS FINE" Seriously guys?

Sorry i haven't been jumping on the answering train here, holidays and noro virus kept my desire to github low.

That said, when i last was using a sony xperia z1 i had this problem fairly often on various sites. Sorry i can't reproduce as i don't have that anymore.
