### ISSUE TITLE
"Read it" links need user input acknowledgement

### ISSUE THREAD

**Issue by wchristian** [dnmfarrell/perldotcom#44]
Right now clicking them doesn't lead to the browser loading anything, but instead just sitting there for a few seconds until JS does the thing. Bad ux. Especially on bad networks where things might just break silently in the background.

**Comment by dnmfarrell** [comment]
I don't know understand, the links are supposed to be plain URLs. Are you seeing something different?

**Comment by briandfoy** [comment]
I don't see anything weird when I try it.

When you report these issues, can you specify the browser that shows the issues? I'm especially interested in any plugins you might have installed that change how your browser acts.

**Comment by dnmfarrell** [comment]
Hey @wchristian are you able to answer our questions above?

**Comment by wchristian** [comment]
Sorry, missed this.

I could swear i saw extremely high pauses between click and activity, in multiple tested browsers (chrome mobile phone, chrome desktop, Opera v12), when i made the ticket.

Currently i see no such thing.

**Comment by briandfoy** [comment]
If it's a problem again we can revisit this.
