### ISSUE TITLE
"LATEST COMMUNITY ARTICLES" block needs better labeling

### ISSUE THREAD

**Issue by wchristian** [dnmfarrell/perldotcom#45]
I thought it was a quicklist of articles on perl.com, but instead it's ... something else?

**Comment by dnmfarrell** [comment]
It's a list of articles on other Perl sites

**Comment by wchristian** [comment]
The question was just an example for my initial train of thought then i saw it. I wasn't asking it to you, but letting you know what impression it left to help guide you towards some improvement.
