### ISSUE TITLE
Add https://mojolicious.io/ as community feed(er)?

### ISSUE THREAD

**Issue by mohawk2** [dnmfarrell/perldotcom#49]

**Comment by dnmfarrell** [comment]
I don't understand this issue, can you elaborate please?

**Comment by mohawk2** [comment]
Sure! I was looking at perl.com and noted on the right the "what's the community up to" feed. The above site is another Perl community blog and I thought it would be suitable to add.

**Comment by dnmfarrell** [comment]
Ah gotcha, ok I've added the RSS feed to [Perly-Bot](/dnmfarrell/Perly-Bot). Thanks!

**Comment by mohawk2** [comment]
@jberger See above!

**Comment by jberger** [comment]
great thanks!
