### ISSUE TITLE
OpenGraph & Twitter Cards

### ISSUE THREAD

**Issue by davorg** [dnmfarrell/perldotcom#53]
Would be good to have OpenGraph and Twitter Card headers, so that Facebook and Twitter show images when the site's content is shared.

I'll have a look to see how easy it is over the next couple of days.

**Comment by dnmfarrell** [comment]
Sounds great, thanks!

**Comment by briandfoy** [comment]
Here's the twitter card info I have on The Effective Perler: Just add the right data in the head and your should be all set. You do need a fancy image too:


    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@briandfoy_perl" />
    <meta name="twitter:creator" content="@briandfoy_perl" />
    <meta name="twitter:url" content="https://www.effectiveperlprogramming.com" />
    <meta name="twitter:title" content="The Effective Perler" />
    <meta name="twitter:description" content="Effective Perl Programming" />
    <meta name="twitter:image"     content="https://www.effectiveperlprogramming.com/images/epp_second_edition.png" />

**Comment by dnmfarrell** [comment]
This mostly seems to work, but the image doesn't load on Twitter's [test site](https://cards-dev.twitter.com/validator), I think it might be because the site config base url does not include www.

**Comment by dnmfarrell** [comment]
That fixed it. think the twitter card info is correct. I have tested it with [facebook's tester](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.perl.com) too.
