### ISSUE TITLE
Convert old SourceForge links to GitHub if the projects have moved

### ISSUE THREAD

**Issue by briandfoy** [dnmfarrell/perldotcom#75]
I was looking at this in my own modules and happened to have a clone of this repo in the same place. These mention sourceforge in some capacity. If it's a link to a repo, check if that's the current link. If it's moved, update the link. If "Sourceforge" is part of the body of the text, make the edit something like "(UPDATE: now at .. )".

- [x] [perldotcom/content/legacy/_pub_2002_03_26_cpanplus.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2002_03_26_cpanplus.md)
- [x] [perldotcom/content/legacy/_pub_2004_11_04_komodo3.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2004_11_04_komodo3.md)
- [x] [perldotcom/content/legacy/_pub_2004_11_18_mod_perlservice.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2004_11_18_mod_perlservice.md)
- [x] [perldotcom/content/legacy/_pub_2001_08_p6pdigest_20010825.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2001_08_p6pdigest_20010825.md)
- [x] [perldotcom/content/legacy/_pub_2006_10_19_cgi_application.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2006_10_19_cgi_application.md)
- [x] [perldotcom/content/legacy/_pub_2004_02_05_siesta.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2004_02_05_siesta.md)
- [x] [perldotcom/content/legacy/_pub_2001_05_p5pdigest_THISWEEK-20010429.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2001_05_p5pdigest_THISWEEK-20010429.md)
- [x] [perldotcom/content/legacy/_pub_2005_08_25_tools.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2005_08_25_tools.md)
- [x] [perldotcom/content/legacy/_pub_2005_07_14_bestpractices.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2005_07_14_bestpractices.md)
- [x] [perldotcom/content/legacy/_pub_2004_10_28_bricolage_installation.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2004_10_28_bricolage_installation.md)
- [x] [perldotcom/content/legacy/_pub_2006_03_02_ajax_and_perl.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2006_03_02_ajax_and_perl.md)
- [x] [perldotcom/content/legacy/_pub_2002_09_11_log4perl.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2002_09_11_log4perl.md)
- [x] [perldotcom/content/legacy/_pub_2005_06_23_sprog.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2005_06_23_sprog.md)
- [x] [perldotcom/content/legacy/_pub_2002_01_23_cgi.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2002_01_23_cgi.md)
- [x] [perldotcom/content/legacy/_pub_2002_03_06_spam.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2002_03_06_spam.md)
- [x] [perldotcom/content/legacy/_pub_2001_10_17_etoys.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2001_10_17_etoys.md)
- [x] [perldotcom/content/legacy/_pub_2001_12_19_xmlrpc.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2001_12_19_xmlrpc.md)
- [x] [perldotcom/content/legacy/_pub_2004_08_27_bricolage.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2004_08_27_bricolage.md)
- [x] [perldotcom/content/legacy/_pub_2003_12_05_slimp3.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2003_12_05_slimp3.md)
- [x] [perldotcom/content/legacy/_pub_2001_09_12_wxtutorial1.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2001_09_12_wxtutorial1.md)
- [x] [perldotcom/content/legacy/_pub_2005_02_p6pdigest_2005031.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2005_02_p6pdigest_2005031.md)
- [x] [perldotcom/content/legacy/_pub_2005_05_19_wireless_gw.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2005_05_19_wireless_gw.md)
- [x] [perldotcom/content/legacy/_pub_2002_08_27_filtering.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2002_08_27_filtering.md)
- [x] [perldotcom/content/legacy/_pub_2002_05_07_optree.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2002_05_07_optree.md)
- [x] [perldotcom/content/legacy/_pub_2001_10_10_perlmx.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2001_10_10_perlmx.md)
- [x] [perldotcom/content/legacy/_pub_2001_12_04_testing.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2001_12_04_testing.md)
- [x] [perldotcom/content/legacy/_pub_2005_03_03_pugs_interview.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2005_03_03_pugs_interview.md)
- [x] [perldotcom/content/legacy/_pub_2003_02_12_module1.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2003_02_12_module1.md)
- [x] [perldotcom/content/legacy/_pub_2002_04_30_cpants.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2002_04_30_cpants.md)
- [x] [perldotcom/content/legacy/_pub_2005_04_21_win32ole.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2005_04_21_win32ole.md)
- [x] [perldotcom/content/legacy/_pub_2005_12_15_perl_prolog.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2005_12_15_perl_prolog.md)
- [x] [perldotcom/content/legacy/_pub_2003_03_p6pdigest_20030316.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2003_03_p6pdigest_20030316.md)
- [x] [perldotcom/content/legacy/_pub_2001_06_05_cgi.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2001_06_05_cgi.md)
- [x] [perldotcom/content/legacy/_pub_2000_12_p5pdigest_THISWEEK-20001225.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2000_12_p5pdigest_THISWEEK-20001225.md)
- [x] [perldotcom/content/legacy/_pub_2005_11_23_bricolage_analysis.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2005_11_23_bricolage_analysis.md)
- [x] [perldotcom/content/legacy/_pub_2005_05_26_word_control.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2005_05_26_word_control.md)
- [x] [perldotcom/content/article/introducing-3-new-perl-glyphs.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/article/introducing-3-new-perl-glyphs.md)
- [x] [perldotcom/content/article/what-s-new-on-cpan---july-2017.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/article/what-s-new-on-cpan---july-2017.md)
- [x] [perldotcom/content/article/create-static-web-apps-with-wget.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/article/create-static-web-apps-with-wget.md)
- [x] [perldotcom/content/article/an-interview-with-peteris-krumins.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/article/an-interview-with-peteris-krumins.md)
- [x] [perldotcom/content/article/what-s-new-on-cpan---february-2015.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/article/what-s-new-on-cpan---february-2015.md)
- [x] [perldotcom/content/article/get-to-grips-with-gnu-screen.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/article/get-to-grips-with-gnu-screen.md)
- [x] [perldotcom/content/article/laptop-review--dell-xps-13-2-in-1--9365-.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/article/laptop-review--dell-xps-13-2-in-1--9365-.md)
- [x] [perldotcom/content/article/perl-jam-iv-return-of-the-camel.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/article/perl-jam-iv-return-of-the-camel.md)
- [x] [perldotcom/content/article/boost-your-perl-productivity-with-auto-compile-checking.md](https://github.com/dnmfarrell/perldotcom/blob/master/content/article/boost-your-perl-productivity-with-auto-compile-checking.md)

**Comment by nanis** [comment]
Should `search.cpan.org` links be converted to `metacpan.org` links?

Also, in [this article](https://github.com/dnmfarrell/perldotcom/blob/master/content/legacy/_pub_2006_10_19_cgi_application.md), the link to `HTML::Template` is to SourceForge. Should that link not be replaced with a link to https://metacpan.org/pod/HTML::Template from where the visitor can find the up to date repo, issue tracker, release download etc?

**Comment by nanis** [comment]
> * HTML::Template - last updated 2002.

Are you sure? The [most recent release][HT] was last year. Current repo [here].

[HT]: https://metacpan.org/pod/HTML::Template
[here]: https://github.com/mpeters/html-template

**Comment by briandfoy** [comment]
Ah, you are right on HTML::Template. I must have seen something outdated. I've fixed up all occurrences.
