### ISSUE TITLE
Need a 404 page

### ISSUE THREAD

**Issue by briandfoy** [dnmfarrell/perldotcom#81]
For instance, https://www.perl.com/pub/2001/10/10/perlmx.htmld

**Comment by dnmfarrell** [comment]
Good point. I'll email the admins and ask if they can configure the webserver to serve a 404 template from the repo.

**Comment by dnmfarrell** [comment]
Sent them an email, awaiting their feedback.

**Comment by dnmfarrell** [comment]
N.B. we do have a [404 template](../blob/master/layouts/404.html), looks like it needs a bit of TLC. https://www.perl.com/404.html

**Comment by dnmfarrell** [comment]
The magic location is `/error/404/html`
